version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-testepratica
    ports:
      - "8008:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db-testepratica
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: testepratica
        MYSQL_USER: ecle
        MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/www/html/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8888:80"